apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
spec:
  default:
    predictor:
      maxReplicas: 1
      minReplicas: 1
      tensorflow:
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
