apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - image: busybox
    name: test-container
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    volumeMounts:
    - mountPath: /tmp
      name: ec2-nfs-pvc
  volumes:
  - name: ec2-nfs-pvc
    persistentVolumeClaim:
      claimName: ec2-nfs-pvc
