apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mariadb-edu00
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      volumes:
      - name: configmap-test
        configMap:
          name: configmap-edu00
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
          name: db-port        
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mariadb-edu00
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-edu00
              key: mysql_zcp
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mariadb-edu00
              key: mysql_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-edu00
              key: basededatos
        volumeMounts:
        - name: configmap-test
          mountPath: /root/
          
