apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-cifar10"
spec:
  default:
    predictor:
      pytorch:
        storageUri: "pvc://vol-my-pvc3/models/pytorch/cifar10/"
        modelClassName: "Net"
