apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-my-pv2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-0880c46ff964d64ea
