apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
  - image: busybox
    name: test-container
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    volumeMounts:
    - mountPath: /tmp
      name: model-pvc
  volumes:
  - name: model-pvc
    persistentVolumeClaim:
      claimName: model-pvc
