apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-09c75aef2967ddd63
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: default 
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
