# export VOLUME_ID=$(aws ec2 create-volume --size 50 --region us-east-1 --availability-zone us-east-1f --volume-type gp2 | jq '.VolumeId' -)


apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      fsType: ext4
      volumeID: <VOLUME_ID> 
