apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: hm-model
spec:
  default:
    predictor:
      #minReplicas: 1
      custom:
        container:
          name: kfserving-container
          image: mokpolar/hm-complete:0.0.1
          resources:
            limits:
              cpu: 1500m
              memory: 10Gi
            requests:
              cpu: 1500m
              memory: 10Gi
#          securityContext:
#            privileged: true
              #allowPrivilegeEscalation: false
         # env:
         ##   - name: STORAGE_URI
         #     value: pvc://nfs-pvc
          #volumeDevices:
          #  - name: nfs
          #    devicePath: pvc://nfs-pvc
#          volumeMounts:
#              - readOnly: true
#                name: nfs
#                mountPath: /mnt

#          args: ["--device=/dev/fuse", "--security-opt", "apparmor:unconfined"]
          #args: ["--privileged", "--cap-add SYS_ADMIN", "--cap-add MKNOD", "--device=/dev/fuse", "--security-opt", "apparmor:unconfined"]
#          env:
#            - name: STORAGE_URI
#              value: pvc://nfs-pvc
