FROM tensorflow/tensorflow:2.1.0-py3

RUN pip install opencv-python
RUN pip install opencv-contrib-python
RUN pip install kfserving==0.3.0 numpy

RUN pip install json



ENV APP_HOME /app
WORKDIR $APP_HOME
ADD simple_mobilenet_transformer.py /app/

ENTRYPOINT ["python", "simple_mobilenet_transformer.py"]