apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: custom-predictor
spec:
  default:
    predictor:
      custom:
        container:
          image: mokpolar/custom-predictor:0.0.1