apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: mnist
spec:
  default:
    predictor:
      minReplicas: 1
      tensorflow:
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        runtimeVersion: 1.14.0
        storageUri: "pvc://my-pvc-b/models/tensorflow/mobilenet/"
    transformer:
      custom:
        container:
          image: mokpolar/kafka-mobilenet-transformer:latest
          name: kfserving-container
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
      minReplicas: 1
