# export VOLUME_ID=$(aws ec2 create-volume --size 50 --region us-east-1 --availability-zone us-east-1f --volume-type gp2 | jq '.VolumeId' -)


apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-b
spec:
  capacity:
    storage: 55Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-0004f2e158a9921c6

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-b
  namespace: kfserving-test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 55Gi
