apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  default:
    predictor:
      triton:
        storageUri: "pvc://my-pvc-a"
        resources:
          limits:
            cpu: "1"
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 10Gi        
