apiVersion: v1
kind: Pod
metadata:
  name: test
  labels: 
    app: test
spec:
  volumes:
  - name: nfs-pvc
    persistentVolumeClaim:
      claimName: nfs-pvc
  containers:
  - image: nginx:alpine
    name: test-container
    volumeMounts:
    - mountPath: /mnt/test
      name: nfs-pvc
