apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "simple-mobilenet-transformer"
spec:
  default:
    predictor:
      minReplicas: 1
      tensorflow:
        storageUri: "pvc://my-pvc-b/models/tensorflow/mobilenet/"
    transformer:
      minReplicas: 1
      custom:
        container:
          image: mokpolar/simple-mobilenet-transformer:0.0.1
  
